// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektCmentarz.Data;

#nullable disable

namespace ProjektCmentarz.Migrations
{
    [DbContext(typeof(GraveyardContext))]
    [Migration("20260314202515_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuneralGravekeeper", b =>
                {
                    b.Property<int>("FuneralId")
                        .HasColumnType("int");

                    b.Property<int>("GravekeeperId")
                        .HasColumnType("int");

                    b.HasKey("FuneralId", "GravekeeperId");

                    b.HasIndex("GravekeeperId");

                    b.ToTable("FuneralGravekeeper");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.ContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactDatas");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Deceased", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Deceaseds");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Funeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FuneralDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuneralPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId")
                        .IsUnique();

                    b.HasIndex("PriestId");

                    b.ToTable("Funerals");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Grave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId");

                    b.HasIndex("PlotId");

                    b.ToTable("Graves");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaintenanceGravekeeperId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceGravekeeperId");

                    b.ToTable("GraveMaintenances");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Gravekeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("GravekeeperContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GravekeeperContactDataId");

                    b.ToTable("Gravekeepers");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveyardSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("GraveyardSections");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GraveyardSectionId")
                        .HasColumnType("int");

                    b.Property<int>("PlotOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraveyardSectionId");

                    b.HasIndex("PlotOwnerId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.PlotOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.ToTable("PlotOwners");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Priest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.ToTable("Priests");
                });

            modelBuilder.Entity("FuneralGravekeeper", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Funeral", null)
                        .WithMany()
                        .HasForeignKey("FuneralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Gravekeeper", null)
                        .WithMany()
                        .HasForeignKey("GravekeeperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Funeral", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Deceased", "Deceased")
                        .WithOne("Funeral")
                        .HasForeignKey("ProjektCmentarz.Models.Funeral", "DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Priest", "FuneralPriest")
                        .WithMany("Funerals")
                        .HasForeignKey("PriestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deceased");

                    b.Navigation("FuneralPriest");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Grave", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Deceased", "GraveDeceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Plot", "GravePlot")
                        .WithMany("Graves")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraveDeceased");

                    b.Navigation("GravePlot");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveMaintenance", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Gravekeeper", "MaintenanceGravekeeper")
                        .WithMany()
                        .HasForeignKey("MaintenanceGravekeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceGravekeeper");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Gravekeeper", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "GravekeeperContactData")
                        .WithMany()
                        .HasForeignKey("GravekeeperContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GravekeeperContactData");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Plot", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.GraveyardSection", null)
                        .WithMany("Plots")
                        .HasForeignKey("GraveyardSectionId");

                    b.HasOne("ProjektCmentarz.Models.PlotOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("PlotOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.PlotOwner", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "OwnerContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerContactData");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Priest", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "PriestContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriestContactData");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Deceased", b =>
                {
                    b.Navigation("Funeral")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveyardSection", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Plot", b =>
                {
                    b.Navigation("Graves");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Priest", b =>
                {
                    b.Navigation("Funerals");
                });
#pragma warning restore 612, 618
        }
    }
}
