// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektCmentarz.Data;

#nullable disable

namespace ProjektCmentarz.Migrations
{
    [DbContext(typeof(GraveyardContext))]
    [Migration("20260516172250_ZmianyUserOrazPlotOwner")]
    partial class ZmianyUserOrazPlotOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuneralGravekeeper", b =>
                {
                    b.Property<int>("FuneralId")
                        .HasColumnType("int");

                    b.Property<int>("GravekeeperId")
                        .HasColumnType("int");

                    b.HasKey("FuneralId", "GravekeeperId");

                    b.HasIndex("GravekeeperId");

                    b.ToTable("FuneralGravekeeper");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.BurialDepth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Depth")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("BurialDepth");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Casket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId")
                        .IsUnique()
                        .HasFilter("[DeceasedId] IS NOT NULL");

                    b.HasIndex("MaterialId");

                    b.ToTable("Casket");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.CauseOfDeath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CausesOfDeath");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.ContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactDatas");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Cremation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CremationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId");

                    b.ToTable("Cremations");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.DeathCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauseOfDeathId")
                        .HasColumnType("int");

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CauseOfDeathId");

                    b.HasIndex("DeceasedId");

                    b.ToTable("DeathCertificates");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Deceased", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CasketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("FuneralId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Deceaseds");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Funeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FuneralDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FuneralHomeId")
                        .HasColumnType("int");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<int>("PriestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId")
                        .IsUnique();

                    b.HasIndex("FuneralHomeId");

                    b.HasIndex("PlotId");

                    b.HasIndex("PriestId");

                    b.ToTable("Funerals");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.FuneralHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("FuneralHomeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.ToTable("FuneralHomes");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Grave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BurialDepthId")
                        .HasColumnType("int");

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BurialDepthId");

                    b.HasIndex("DeceasedId");

                    b.HasIndex("PlotId");

                    b.ToTable("Graves");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaintenanceGravekeeperId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceGravekeeperId");

                    b.ToTable("GraveMaintenances");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Gravekeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("TransferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.HasIndex("TransferId");

                    b.ToTable("Gravekeepers");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Gravestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<int>("GraveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("GraveId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Gravestones");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GravestoneInscryption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Inscryption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GravestoneInscryptions");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveyardSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GraveyardSection");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GraveId")
                        .HasColumnType("int");

                    b.Property<int>("GravekeepId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GraveId");

                    b.HasIndex("GravekeepId");

                    b.ToTable("MaintenanceRequests");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Ownership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GraveId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.HasIndex("GraveId");

                    b.ToTable("Ownerships");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Parish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Parishes");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GraveyardSectionId")
                        .HasColumnType("int");

                    b.Property<int?>("PlotOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraveyardSectionId");

                    b.HasIndex("PlotOwnerId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.PlotOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.HasIndex("UserId");

                    b.ToTable("PlotOwners");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Priest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ParishId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDataId");

                    b.HasIndex("ParishId");

                    b.ToTable("Priests");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<int>("FromGraveId")
                        .HasColumnType("int");

                    b.Property<int>("ToGraveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId");

                    b.HasIndex("FromGraveId");

                    b.HasIndex("ToGraveId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("ContactDataId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("ContactDataId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("FuneralGravekeeper", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Funeral", null)
                        .WithMany()
                        .HasForeignKey("FuneralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Gravekeeper", null)
                        .WithMany()
                        .HasForeignKey("GravekeeperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Casket", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Deceased", "Deceased")
                        .WithOne("Casket")
                        .HasForeignKey("ProjektCmentarz.Models.Casket", "DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjektCmentarz.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deceased");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Cremation", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Deceased", "Deceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deceased");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.DeathCertificate", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.CauseOfDeath", "CauseOfDeath")
                        .WithMany()
                        .HasForeignKey("CauseOfDeathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Deceased", "Deceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauseOfDeath");

                    b.Navigation("Deceased");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Funeral", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Deceased", "Deceased")
                        .WithOne("Funeral")
                        .HasForeignKey("ProjektCmentarz.Models.Funeral", "DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjektCmentarz.Models.FuneralHome", null)
                        .WithMany("Funerals")
                        .HasForeignKey("FuneralHomeId");

                    b.HasOne("ProjektCmentarz.Models.Plot", "FuneralPlot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Priest", "FuneralPriest")
                        .WithMany("Funerals")
                        .HasForeignKey("PriestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deceased");

                    b.Navigation("FuneralPlot");

                    b.Navigation("FuneralPriest");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.FuneralHome", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "FuneralHomeContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuneralHomeContactData");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Grave", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.BurialDepth", "BurialDepth")
                        .WithMany()
                        .HasForeignKey("BurialDepthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Deceased", "GraveDeceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Plot", "GravePlot")
                        .WithMany("Graves")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BurialDepth");

                    b.Navigation("GraveDeceased");

                    b.Navigation("GravePlot");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveMaintenance", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Gravekeeper", "MaintenanceGravekeeper")
                        .WithMany()
                        .HasForeignKey("MaintenanceGravekeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceGravekeeper");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Gravekeeper", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "GravekeeperContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Transfer", null)
                        .WithMany("TransferGravekeepers")
                        .HasForeignKey("TransferId");

                    b.Navigation("GravekeeperContactData");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Gravestone", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Grave", "Grave")
                        .WithMany()
                        .HasForeignKey("GraveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Grave");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Grave", "Grave")
                        .WithMany()
                        .HasForeignKey("GraveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Gravekeeper", "Gravekeeper")
                        .WithMany()
                        .HasForeignKey("GravekeepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grave");

                    b.Navigation("Gravekeeper");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Ownership", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "ContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Grave", "Grave")
                        .WithMany()
                        .HasForeignKey("GraveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactData");

                    b.Navigation("Grave");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Plot", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.GraveyardSection", "GraveyardSection")
                        .WithMany("Plots")
                        .HasForeignKey("GraveyardSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.PlotOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("PlotOwnerId");

                    b.Navigation("GraveyardSection");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.PlotOwner", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "OwnerContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("OwnerContactData");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Priest", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "PriestContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Parish", "Parish")
                        .WithMany()
                        .HasForeignKey("ParishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parish");

                    b.Navigation("PriestContactData");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Reservation", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Transfer", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Deceased", "Deceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Grave", "TransferFromGrave")
                        .WithMany()
                        .HasForeignKey("FromGraveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.Grave", "TransferToGrave")
                        .WithMany()
                        .HasForeignKey("ToGraveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deceased");

                    b.Navigation("TransferFromGrave");

                    b.Navigation("TransferToGrave");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.User", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.ContactData", "UserContactData")
                        .WithMany()
                        .HasForeignKey("ContactDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserContactData");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("ProjektCmentarz.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektCmentarz.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Deceased", b =>
                {
                    b.Navigation("Casket");

                    b.Navigation("Funeral");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.FuneralHome", b =>
                {
                    b.Navigation("Funerals");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.GraveyardSection", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Plot", b =>
                {
                    b.Navigation("Graves");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Priest", b =>
                {
                    b.Navigation("Funerals");
                });

            modelBuilder.Entity("ProjektCmentarz.Models.Transfer", b =>
                {
                    b.Navigation("TransferGravekeepers");
                });
#pragma warning restore 612, 618
        }
    }
}
